### PR TITLE
feat: bump provider version and disable skip of cloud shell call

### PR DESCRIPTION
**Pull request by vburckhardt**
### Description

https://github.com/IBM-Cloud/terraform-provider-ibm/releases/tag/v1.65.1 contains the fix at provider level for the cs issues, so re-enabling cs handling here as well.

### CODE REVIEW

**Review by rajatagarwal-ibm — APPROVED** [review]

**Review by ocofaigh — DISMISSED** [review]

**Comment by vburckhardt** [comment]
Ok putting this on on hold  - issue is not fixed in 1.65.1

```
 TestRunDA 2024-05-17T10:20:35Z logger.go:66: ╷
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ Error: Plugin did not respond
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │   with module.account_infrastructure_base.module.account_settings.ibm_cloud_shell_account_settings.cloud_shell_account_settings[0],
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │   on .terraform/modules/account_infrastructure_base.account_settings/main.tf line 39, in resource "ibm_cloud_shell_account_settings" "cloud_shell_account_settings":
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │   39: resource "ibm_cloud_shell_account_settings" "cloud_shell_account_settings" {
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ The plugin encountered an error, and failed to respond to the
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
TestRunDA 2024-05-17T10:20:35Z logger.go:66: │ contain more details.
TestRunDA 2024-05-17T10:20:35Z logger.go:66: ╵
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: Stack trace from the terraform-provider-ibm_v1.65.1 plugin:
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: panic: runtime error: invalid memory address or nil pointer dereference
TestRunDA 2024-05-17T10:20:35Z logger.go:66: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2339b1d]
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: goroutine 151 [running]:
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cloudshell.resourceIBMCloudShellAccountSettingsCreate({0x520fd98, 0xc002404720}, 0x1176592e000?, {0x4885ea0?, 0xc000454000})
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/cloudshell/resource_ibm_cloud_shell_account_settings.go:172 +0x6dd
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/IBM-Cloud/terraform-provider-ibm/ibm/provider.wrapFunction.func1({0x520fd98?, 0xc002404720?}, 0x0?, {0x4885ea0?, 0xc000454000?})
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/IBM-Cloud/terraform-provider-ibm/ibm/provider/provider.go:1533 +0x32
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0015e7260, {0x520fdd0, 0xc001b65770}, 0xd?, {0x4885ea0, 0xc000454000})
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:778 +0x12e
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0015e7260, {0x520fdd0, 0xc001b65770}, 0xc002417790, 0xc0017ee680, {0x4885ea0, 0xc000454000})
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa85
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000c3a9c0, {0x520fdd0?, 0xc001b65320?}, 0xc002155b80)
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000b00000, {0x520fdd0?, 0xc001b64630?}, 0xc00241c3f0)
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
TestRunDA 2024-05-17T10:20:35Z logger.go:66: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x46fe9e0?, 0xc000b00000}, {0x520fdd0, 0xc001b64630}, 0xc00241c380, 0x0)
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
TestRunDA 2024-05-17T10:20:35Z logger.go:66: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002243c0, {0x521abe0, 0xc000a0e680}, 0xc0019f4fc0, 0xc0015b36e0, 0x726d098, 0x0)
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	google.golang.org/grpc@v1.57.1/server.go:1358 +0xe23
TestRunDA 2024-05-17T10:20:35Z logger.go:66: google.golang.org/grpc.(*Server).handleStream(0xc0002243c0, {0x521abe0, 0xc000a0e680}, 0xc0019f4fc0, 0x0)
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	google.golang.org/grpc@v1.57.1/server.go:1735 +0xa2f
TestRunDA 2024-05-17T10:20:35Z logger.go:66: google.golang.org/grpc.(*Server).serveStreams.func1.1()
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	google.golang.org/grpc@v1.57.1/server.go:970 +0xca
TestRunDA 2024-05-17T10:20:35Z logger.go:66: created by google.golang.org/grpc.(*Server).serveStreams.func1
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 	google.golang.org/grpc@v1.57.1/server.go:981 +0x15c
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: Error: The terraform-provider-ibm_v1.65.1 plugin crashed!
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z logger.go:66: This is always indicative of a bug within the plugin. It would be immensely
TestRunDA 2024-05-17T10:20:35Z logger.go:66: helpful if you could report the crash with the plugin's maintainers so that it
TestRunDA 2024-05-17T10:20:35Z logger.go:66: can be fixed. The output above should help diagnose the issue.
TestRunDA 2024-05-17T10:20:35Z logger.go:66: 
TestRunDA 2024-05-17T10:20:35Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Plugin did not respond
```

**Comment by ocofaigh** [comment]
Ah no - Ive let the provider team know and left a [comment](https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5349#issuecomment-2117260507)

**Comment by ocofaigh** [comment]
The backend issue has been resolved - so we should proceed with resolving conflicts here and merging this

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
