### PR TITLE
feat: skip_cloud_shell_calls defaults to true

### PR DESCRIPTION
**Pull request by jor2**
### Description

Since the account infrastructure base DA https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/issues/301with cloud shell settings when using a service ID (or trusted profile), the default for skip_cloud_shell_calls should be set to true.
https://github.com/terraform-ibm-modules/dev-rag/issues/14

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Default value for cloud shell settings set to true.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by toddgiguere — APPROVED** [review]

**Comment by jor2** [comment]
this was the error:
````
        	Test:       	TestRunUpgradeDA
        	Messages:   	Resource(s) identified to be destroyed 
        	            	Name: cloud_shell_account_settings
        	            	Address: module.account_infrastructure_base.module.account_settings[0].ibm_cloud_shell_account_settings.cloud_shell_account_settings[0]
        	            	Actions: [delete]
````
looks like it does a delete on existing resource so it would be breaking change

**Pull request merged**
