### PR TITLE
[DO NOT MERGE] ci: onboard to catalog pipeline

### PR DESCRIPTION
**Pull request by ocofaigh**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — COMMENTED** [review]
@MatthewLemmond This is assuming that `solutions/standard` is location of DA, and that a diagram exists in `https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-base-account-enterprise/main/reference-architecture/diagram.svg` (both can be changed depending on what comes in your PR)

**Comment by MatthewLemmond** [comment]
> This is assuming that `solutions/standard` is location of DA, and that a diagram exists in `https://raw.githubusercontent.com/terraform-ibm-modules/terraform-ibm-base-account-enterprise/main/reference-architecture/diagram.svg` (both can be changed depending on what comes in your PR)

name will be `account-infrastructure-base`

**Comment by ocofaigh** [comment]
Depends on https://github.com/terraform-ibm-modules/terraform-ibm-base-account-enterprise/pull/22 (we might merge this into that PR)

**Comment by ocofaigh** [comment]
changes coming directly in https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/23

**Pull request closed without merging**
