### PR TITLE
fix: fixes typo error in reference-architectures

### PR DESCRIPTION
**Pull request by Khuzaima05**
### Description

issue : https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/issues/120

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
looks like resource group icon is missing?

**Comment by Khuzaima05** [comment]
> looks like resource group icon is missing?

@ocofaigh , we are not using the icon as per these reference architecture : 

- terraform-ibm-cos:  https://github.com/terraform-ibm-modules/terraform-ibm-cos/blob/main/reference-architectures/secure-cross-regional-bucket.svg   
- ElasticSearch module: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/blob/main/reference-architecture/deployable-architecture-elasticsearch.svg
- Observability da: https://github.com/terraform-ibm-modules/terraform-ibm-observability-da/blob/main/reference-architecture/deployable-architecture-observability-instances.svg

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
